import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'
import { createCalendarEvent, isCalendarConnected } from '@/lib/integrations/google-calendar'

export async function GET(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const searchParams = request.nextUrl.searchParams
  const clientId = searchParams.get('client_id')
  const status = searchParams.get('status')
  const search = searchParams.get('search')

  let query = supabase
    .from('hub_meetings')
    .select(`
      *,
      hub_clients!inner(id, nome_cliente, nome_empresa)
    `)
    .order('meeting_date', { ascending: false })

  if (clientId) query = query.eq('client_id', clientId)
  if (status) query = query.eq('status', status)
  if (search) query = query.ilike('title', `%${search}%`)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json(data)
}

export async function POST(request: NextRequest) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await request.json()

  // Get client email for calendar invite
  const { data: clientData } = await supabase
    .from('hub_clients')
    .select('email, nome_empresa, nome_cliente')
    .eq('id', body.client_id)
    .single()

  let meetLink = body.google_meet_link || null
  let calendarEventId: string | null = null
  let calendarHtmlLink: string | null = null
  let calendarSynced = false

  // Try to create Google Calendar event if connected
  const connected = await isCalendarConnected()
  if (connected && body.meeting_date) {
    const calResult = await createCalendarEvent({
      title: body.title,
      description: `Reunião com ${clientData?.nome_empresa || clientData?.nome_cliente || 'cliente'}`,
      startDateTime: body.meeting_date,
      durationMinutes: body.duration_minutes || 60,
      clientEmail: clientData?.email || null,
      meetLink,
    })

    if (calResult.success) {
      calendarEventId = calResult.eventId || null
      calendarHtmlLink = calResult.htmlLink || null
      calendarSynced = true
      // Use Meet link generated by Google if not manually provided
      if (!meetLink && calResult.meetLink) {
        meetLink = calResult.meetLink
      }
    }
  }

  const { data: meeting, error } = await supabase
    .from('hub_meetings')
    .insert({
      client_id: body.client_id,
      user_id: user.id,
      title: body.title,
      meeting_date: body.meeting_date,
      duration_minutes: body.duration_minutes || null,
      google_meet_link: meetLink,
      status: body.status || 'scheduled',
      metadata: {
        ...(body.metadata || {}),
        calendar_event_id: calendarEventId,
        calendar_html_link: calendarHtmlLink,
        calendar_synced: calendarSynced,
      },
    })
    .select(`
      *,
      hub_clients!inner(id, nome_cliente, nome_empresa)
    `)
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  await supabase.from('hub_timeline_events').insert({
    client_id: body.client_id,
    user_id: user.id,
    event_type: 'meeting_recorded',
    title: `Reunião agendada: ${body.title}`,
    description: `Agendada para ${new Date(body.meeting_date).toLocaleDateString('pt-BR')}${calendarSynced ? ' • Sincronizado com Google Calendar' : ''}`,
  })

  return NextResponse.json({ ...meeting, calendar_synced: calendarSynced }, { status: 201 })
}
